<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Trading.Workers.MarketData-f76f9ea8-dab7-4839-9c14-d4bb7628dfc6</UserSecretsId>
    <NoWarn>$(NoWarn);CA1515</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trading.Exchanges.Kraken\Trading.Exchanges.Kraken.csproj" />
    <ProjectReference Include="..\Trading.Infrastructure.Data\Trading.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\Trading.MarketData\Trading.MarketData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Trading.ArchitectureTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
