// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Infrastructure.Data;

#nullable disable

namespace Trading.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20261003190014_PlanEntitlements")]
    partial class PlanEntitlements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trading.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("After")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Before")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Entitlements.Entitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("TrialExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("Entitlements", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Entitlements.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("FuturesEligible")
                        .HasColumnType("bit");

                    b.Property<bool>("LiveTradingEligible")
                        .HasColumnType("bit");

                    b.Property<int>("MaxExperimentWorkers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Execution.OrderReconciliationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExchangeOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ObservedStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ResolvedAtUtc");

                    b.ToTable("OrderReconciliations", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("CloseOnly")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ExchangeAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExchangeOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("FilledQuantity")
                        .HasColumnType("decimal(28,8)");

                    b.Property<DateTimeOffset?>("LastTransitionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("ReconciliationReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("ReduceOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresReconciliation")
                        .HasColumnType("bit");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("UserId", "Mode");

                    b.HasIndex("UserId", "RequiresReconciliation");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(28,8)");

                    b.Property<DateTimeOffset?>("LastTransitionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("MarkPrice")
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("StopLossPrice")
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("TakeProfitPrice")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("UnrealizedPnl")
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Mode");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Users.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("MultiFactorAuthenticationEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReportingCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Trading.Exchanges.Abstractions.ExchangeAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExchangeKind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastValidatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ProvingNotionalCeiling")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StageChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExchangeKind");

                    b.ToTable("ExchangeAccounts", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.AdministratorMfaRedemption", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TimeStep")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UsedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "TimeStep");

                    b.ToTable("AdministratorMfaRedemptions", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Backtesting.PersistedHistoricalDataset", b =>
                {
                    b.Property<string>("VersionIdentity")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CandleCount")
                        .HasColumnType("int");

                    b.Property<bool>("ContainsOnlyClosedCandles")
                        .HasColumnType("bit");

                    b.Property<string>("ContentFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ToUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("VersionIdentity");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Symbol", "Interval", "FromUtc", "ToUtc", "CreatedAtUtc", "VersionIdentity");

                    b.ToTable("HistoricalDatasets", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedExperimentDecisionRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupConfigurationVersion")
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<string>("StrategyId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StrategyVersion")
                        .HasColumnType("int");

                    b.Property<string>("StrategyFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OpenTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CloseTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "WorkerId", "GroupConfigurationVersion", "Group", "StrategyId", "StrategyVersion", "StrategyFingerprint", "Symbol", "Interval", "OpenTimeUtc", "CloseTimeUtc", "AsOfUtc");

                    b.HasIndex("UserId", "WorkerId", "AsOfUtc");

                    b.ToTable("ExperimentDecisionRecords", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedExperimentPaperExecutionAssociation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupConfigurationVersion")
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<string>("StrategyId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StrategyVersion")
                        .HasColumnType("int");

                    b.Property<string>("StrategyFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OpenTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CloseTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("ExecutionCommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "WorkerId", "GroupConfigurationVersion", "Group", "StrategyId", "StrategyVersion", "StrategyFingerprint", "Symbol", "Interval", "OpenTimeUtc", "CloseTimeUtc", "AsOfUtc");

                    b.HasIndex("UserId", "WorkerId", "AsOfUtc");

                    b.ToTable("ExperimentPaperExecutionAssociations", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedExperimentPaperPlanEvidence", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupConfigurationVersion")
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<string>("StrategyId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StrategyVersion")
                        .HasColumnType("int");

                    b.Property<string>("StrategyFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OpenTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CloseTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ConservativeTargetPrice")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("ProtectiveStopPrice")
                        .HasColumnType("decimal(28,8)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "WorkerId", "GroupConfigurationVersion", "Group", "StrategyId", "StrategyVersion", "StrategyFingerprint", "Symbol", "Interval", "OpenTimeUtc", "CloseTimeUtc", "AsOfUtc");

                    b.HasIndex("UserId", "WorkerId", "AsOfUtc");

                    b.ToTable("ExperimentPaperPlanEvidence", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedExperimentResultSnapshot", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SnapshotKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Cash")
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("ClassifierVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DatasetFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Equity")
                        .HasColumnType("decimal(28,8)");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("Exposure")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("GateEvidenceFingerprint")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("GateFailureCount")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("GroupConfigurationVersion")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaximumDrawdown")
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("ParametersFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("PositionQuantity")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("RealizedProfitAndLoss")
                        .HasColumnType("decimal(28,8)");

                    b.Property<int?>("RejectedActionCount")
                        .HasColumnType("int");

                    b.Property<int?>("RejectedFillCount")
                        .HasColumnType("int");

                    b.Property<string>("ReproducibilityIdentity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.Property<decimal?>("Slippage")
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StrategyVersion")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnrealizedProfitAndLoss")
                        .HasColumnType("decimal(28,8)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OwnerUserId", "SnapshotKey");

                    b.HasIndex("OwnerUserId", "EvaluatedAtUtc");

                    b.ToTable("ExperimentResultSnapshots", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedExperimentWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("MarketSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MaxAdditionsPerPosition")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxPositionNotional")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("MaxPositionQuantity")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("MaxTotalPurchasedNotional")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("MaxTotalPurchasedQuantity")
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("int");

                    b.Property<decimal>("StartingCash")
                        .HasColumnType("decimal(28,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StrategyParameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Id")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("ExperimentWorkers", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedPaperTradingLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("ExecutionPrice")
                        .HasColumnType("decimal(28,8)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(28,8)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(28,8)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("UserId", "WorkerId", "OccurredAtUtc", "Id");

                    b.ToTable("ExperimentPaperTradingLedgerEntries", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedPaperTrainingActivation", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ApprovedResearchGroupsAndGates")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DurableClosedCandleSource")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputLedger")
                        .HasColumnType("bit");

                    b.Property<bool>("PaperFillPolicy")
                        .HasColumnType("bit");

                    b.Property<bool>("ProtectiveScheduler")
                        .HasColumnType("bit");

                    b.Property<string>("QualificationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SlotCount")
                        .HasColumnType("int");

                    b.Property<string>("SlotsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StrategyAssignmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WorkerRiskPolicy")
                        .HasColumnType("bit");

                    b.HasKey("OwnerUserId");

                    b.ToTable("PaperTrainingActivations", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.MarketData.PersistedCandle", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OpenTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(28,12)");

                    b.Property<DateTimeOffset>("CloseTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(28,12)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("bit");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(28,12)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(28,12)");

                    b.Property<string>("QualityFlags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(28,12)");

                    b.HasKey("Symbol", "Interval", "OpenTimeUtc");

                    b.HasIndex("Symbol", "Interval", "CloseTimeUtc", "OpenTimeUtc");

                    b.ToTable("Candles", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Scanner.PersistedScanRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ResultLimit")
                        .HasColumnType("int");

                    b.Property<string>("Symbols")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAtUtc", "Id");

                    b.ToTable("ScanRequests", (string)null);
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Scanner.PersistedScanResult", b =>
                {
                    b.Property<Guid>("ScanRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EvidenceAsOfUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MatchedCriteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,12)");

                    b.HasKey("ScanRequestId", "ScanRunId", "Symbol");

                    b.HasIndex("OwnerId", "ScanRequestId", "ScanRunId", "Rank", "Score", "Symbol");

                    b.ToTable("ScanResults", (string)null);
                });

            modelBuilder.Entity("Trading.Domain.Entitlements.Entitlement", b =>
                {
                    b.HasOne("Trading.Domain.Entitlements.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trading.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.AdministratorMfaRedemption", b =>
                {
                    b.HasOne("Trading.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedPaperTradingLedgerEntry", b =>
                {
                    b.HasOne("Trading.Infrastructure.Data.Experiments.PersistedExperimentWorker", null)
                        .WithMany("LedgerEntries")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trading.Infrastructure.Data.Experiments.PersistedExperimentWorker", b =>
                {
                    b.Navigation("LedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
